name: "Greet User"
description: "Prints a greeting using the provided name"
inputs:
  name:
    description: "Name of the user to greet"
    required: true
    default: "World"
outputs:
  greeting:
    description: "The constructed greeting"
    value: ${{ steps.set-greeting.outputs.greeting }}
runs:
  using: "composite"
  steps:
    - name: Print greeting
      id: set-greeting
      run: |
        echo "Hello, ${{ inputs.name }}!"
        echo "greeting=Hello, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
      shell: bash

